new lock file

diff --git a/.github/workflows/deploy-docs.yaml b/.github/workflows/deploy-docs.yaml
--- a/.github/workflows/deploy-docs.yaml
+++ b/.github/workflows/deploy-docs.yaml
@@ -45,7 +45,10 @@ jobs:
         env:
           SPHINXOPTS: "-W --keep-going"
         run: uv run make deploy
-
+      - name: List built docs
+        run: ls -R .
+      - name: Check what site/build/html contains
+        run: ls -R site/build/html || echo "NOT FOUND"
       - name: GitHub Pages action
         uses: peaceiris/actions-gh-pages@v4.0.0
         with:
